help:
    @just --list

lint:
    uv run ruff format --check
    uv run ruff check
    uv run basedpyright

fmt:
    uv run ruff check --select I --fix --exit-zero
    uv run ruff check --fix --exit-zero
    uv run ruff format
