[project]
name = "name-of-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Sias Mey", email = "siasmey@gmail.com" }]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["basedpyright>=1.31.3", "ruff>=0.12.10"]
