[lint]
select = ["ALL"]
ignore = [
  "W191",
  "E111",
  "E114",
  "E117",
  "D206",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "E501",
]

[lint.pydocstyle]
convention = "google"
